### ISSUE TITLE
Compile on linux, Ubuntu 18.04.3

### ISSUE THREAD

**Issue by igoumeninja** [mgs/ofxMLTK#4]
Dear Michael, I try to run the example on my machine. The first error was:
`of_v0.11.0_linux64gcc6_release/addons/ofxMLTK/libs/ffmpeg/include/libavutil/time.h:25:10: fatal error: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/time.h: No such file or directory
 #include </Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/time.h>
`
I comment this line and I uncomment the next one:
`#include </usr/include/time.h>`.

After that I recompile and I get the following error:
`oF_apps/machineListening/src/ofApp.cpp:21:44: error: no matching function for call to ‘MLTK::setup(int&, int&, int&)’
   mltk.setup(frameSize, sampleRate, hopSize);
`

Any help? 
Thanks in advance.
Aris
